name: Build Wheelhouse

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Set archive name
        shell: powershell
        run: |
          $repo = "${{ github.event.repository.name }}"
          $archive = "$repo-requirements-python312-win64.zip"

          echo "ARCHIVE_NAME=$archive" >> $env:GITHUB_ENV

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip

      - name: Download packages
        run: |
          pip download -r requirements.txt -d wheelhouse

      - name: Compress wheelhouse
        shell: powershell
        run: |
          Compress-Archive `
            -Path wheelhouse `
            -DestinationPath $env:ARCHIVE_NAME

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: requirements-python312-win64
          path: ${{ env.ARCHIVE_NAME }}